"""add requirements and quotes

Revision ID: 05c8141387bc
Revises: b54a0dbc0311
Create Date: 2026-04-16 00:43:30.031029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c8141387bc'
down_revision: Union[str, None] = 'b54a0dbc0311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('number_of_workers', sa.Integer(), nullable=False),
    sa.Column('work_location', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('shift_details', sa.String(length=255), nullable=True),
    sa.Column('food_required', sa.Boolean(), nullable=False),
    sa.Column('accommodation_required', sa.Boolean(), nullable=False),
    sa.Column('budget_amount', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_category'), 'requirements', ['category'], unique=False)
    op.create_index(op.f('ix_requirements_city'), 'requirements', ['city'], unique=False)
    op.create_index(op.f('ix_requirements_client_id'), 'requirements', ['client_id'], unique=False)
    op.create_index(op.f('ix_requirements_created_by_user_id'), 'requirements', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_requirements_id'), 'requirements', ['id'], unique=False)
    op.create_index(op.f('ix_requirements_state'), 'requirements', ['state'], unique=False)
    op.create_index(op.f('ix_requirements_status'), 'requirements', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('quoted_amount', sa.Integer(), nullable=False),
    sa.Column('advance_amount', sa.Integer(), nullable=True),
    sa.Column('payment_model', sa.String(length=50), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('terms_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_created_by_user_id'), 'quotes', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_requirement_id'), 'quotes', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_requirement_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_created_by_user_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_requirements_status'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_state'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_created_by_user_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_client_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_city'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_category'), table_name='requirements')
    op.drop_table('requirements')
    # ### end Alembic commands ###
