"""add payment tables

Revision ID: 09358c51a003
Revises: f6a1d00b622a
Create Date: 2026-04-16 01:13:40.437521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09358c51a003'
down_revision: Union[str, None] = 'f6a1d00b622a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_model', sa.String(length=50), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_signature', sa.String(length=255), nullable=True),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_payments_client_id'), 'client_payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_payments_gateway_order_id'), 'client_payments', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_client_payments_gateway_payment_id'), 'client_payments', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_client_payments_id'), 'client_payments', ['id'], unique=False)
    op.create_index(op.f('ix_client_payments_payment_mode'), 'client_payments', ['payment_mode'], unique=False)
    op.create_index(op.f('ix_client_payments_payment_model'), 'client_payments', ['payment_model'], unique=False)
    op.create_index(op.f('ix_client_payments_payment_status'), 'client_payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_client_payments_requirement_id'), 'client_payments', ['requirement_id'], unique=False)
    op.create_table('worker_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_item_id', sa.Integer(), nullable=False),
    sa.Column('worker_profile_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payout_mode', sa.String(length=50), nullable=False),
    sa.Column('payout_status', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_item_id'], ['payroll_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_profile_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_payouts_id'), 'worker_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_worker_payouts_payout_mode'), 'worker_payouts', ['payout_mode'], unique=False)
    op.create_index(op.f('ix_worker_payouts_payout_status'), 'worker_payouts', ['payout_status'], unique=False)
    op.create_index(op.f('ix_worker_payouts_payroll_item_id'), 'worker_payouts', ['payroll_item_id'], unique=False)
    op.create_index(op.f('ix_worker_payouts_transaction_reference'), 'worker_payouts', ['transaction_reference'], unique=False)
    op.create_index(op.f('ix_worker_payouts_worker_profile_id'), 'worker_payouts', ['worker_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_payouts_worker_profile_id'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_transaction_reference'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_payroll_item_id'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_payout_status'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_payout_mode'), table_name='worker_payouts')
    op.drop_index(op.f('ix_worker_payouts_id'), table_name='worker_payouts')
    op.drop_table('worker_payouts')
    op.drop_index(op.f('ix_client_payments_requirement_id'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_payment_status'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_payment_model'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_payment_mode'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_id'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_gateway_payment_id'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_gateway_order_id'), table_name='client_payments')
    op.drop_index(op.f('ix_client_payments_client_id'), table_name='client_payments')
    op.drop_table('client_payments')
    # ### end Alembic commands ###
