"""add profile tables

Revision ID: b54a0dbc0311
Revises: 198edc44ae23
Create Date: 2026-04-16 00:37:36.417522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54a0dbc0311'
down_revision: Union[str, None] = '198edc44ae23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_profiles_id'), 'admin_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_admin_profiles_user_id'), 'admin_profiles', ['user_id'], unique=True)
    op.create_table('client_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_profiles_city'), 'client_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_client_profiles_company_name'), 'client_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_client_profiles_id'), 'client_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_client_profiles_state'), 'client_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_client_profiles_user_id'), 'client_profiles', ['user_id'], unique=True)
    op.create_table('worker_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_notes', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_profiles_category'), 'worker_profiles', ['category'], unique=False)
    op.create_index(op.f('ix_worker_profiles_city'), 'worker_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_worker_profiles_full_name'), 'worker_profiles', ['full_name'], unique=False)
    op.create_index(op.f('ix_worker_profiles_id'), 'worker_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_worker_profiles_state'), 'worker_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_worker_profiles_user_id'), 'worker_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_worker_profiles_verification_status'), 'worker_profiles', ['verification_status'], unique=False)
    op.create_table('worker_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_profile_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_profile_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_documents_document_type'), 'worker_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_worker_documents_id'), 'worker_documents', ['id'], unique=False)
    op.create_index(op.f('ix_worker_documents_verification_status'), 'worker_documents', ['verification_status'], unique=False)
    op.create_index(op.f('ix_worker_documents_worker_profile_id'), 'worker_documents', ['worker_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_documents_worker_profile_id'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_verification_status'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_id'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_document_type'), table_name='worker_documents')
    op.drop_table('worker_documents')
    op.drop_index(op.f('ix_worker_profiles_verification_status'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_user_id'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_state'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_id'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_full_name'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_city'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_category'), table_name='worker_profiles')
    op.drop_table('worker_profiles')
    op.drop_index(op.f('ix_client_profiles_user_id'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_state'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_id'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_company_name'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_city'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_admin_profiles_user_id'), table_name='admin_profiles')
    op.drop_index(op.f('ix_admin_profiles_id'), table_name='admin_profiles')
    op.drop_table('admin_profiles')
    # ### end Alembic commands ###
