"""add payment gateway uniqueness

Revision ID: b68be383153e
Revises: c8bcd9828176
Create Date: 2026-04-16 01:31:36.790931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68be383153e'
down_revision: Union[str, None] = 'c8bcd9828176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_client_payments_gateway_order_id', 'client_payments', ['gateway_order_id'])
    op.create_unique_constraint('uq_client_payments_gateway_payment_id', 'client_payments', ['gateway_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_payments_gateway_payment_id', 'client_payments', type_='unique')
    op.drop_constraint('uq_client_payments_gateway_order_id', 'client_payments', type_='unique')
    # ### end Alembic commands ###
