"""add complaints and replacements

Revision ID: c8bcd9828176
Revises: 09358c51a003
Create Date: 2026-04-16 01:21:07.171881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bcd9828176'
down_revision: Union[str, None] = '09358c51a003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('raised_by_user_id', sa.Integer(), nullable=False),
    sa.Column('complaint_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_assignment_id'), 'complaints', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_type'), 'complaints', ['complaint_type'], unique=False)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_index(op.f('ix_complaints_raised_by_user_id'), 'complaints', ['raised_by_user_id'], unique=False)
    op.create_index(op.f('ix_complaints_requirement_id'), 'complaints', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_complaints_severity'), 'complaints', ['severity'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('replacements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('old_assignment_id', sa.Integer(), nullable=False),
    sa.Column('new_assignment_id', sa.Integer(), nullable=True),
    sa.Column('old_worker_profile_id', sa.Integer(), nullable=False),
    sa.Column('new_worker_profile_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['new_assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_worker_profile_id'], ['worker_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['old_worker_profile_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replacements_complaint_id'), 'replacements', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_replacements_created_by_user_id'), 'replacements', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_replacements_id'), 'replacements', ['id'], unique=False)
    op.create_index(op.f('ix_replacements_new_assignment_id'), 'replacements', ['new_assignment_id'], unique=False)
    op.create_index(op.f('ix_replacements_new_worker_profile_id'), 'replacements', ['new_worker_profile_id'], unique=False)
    op.create_index(op.f('ix_replacements_old_assignment_id'), 'replacements', ['old_assignment_id'], unique=False)
    op.create_index(op.f('ix_replacements_old_worker_profile_id'), 'replacements', ['old_worker_profile_id'], unique=False)
    op.create_index(op.f('ix_replacements_status'), 'replacements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replacements_status'), table_name='replacements')
    op.drop_index(op.f('ix_replacements_old_worker_profile_id'), table_name='replacements')
    op.drop_index(op.f('ix_replacements_old_assignment_id'), table_name='replacements')
    op.drop_index(op.f('ix_replacements_new_worker_profile_id'), table_name='replacements')
    op.drop_index(op.f('ix_replacements_new_assignment_id'), table_name='replacements')
    op.drop_index(op.f('ix_replacements_id'), table_name='replacements')
    op.drop_index(op.f('ix_replacements_created_by_user_id'), table_name='replacements')
    op.drop_index(op.f('ix_replacements_complaint_id'), table_name='replacements')
    op.drop_table('replacements')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_severity'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_requirement_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_raised_by_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_type'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assignment_id'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
