"""add payroll tables

Revision ID: f6a1d00b622a
Revises: a6bb14786944
Create Date: 2026-04-16 01:08:33.804552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a1d00b622a'
down_revision: Union[str, None] = 'a6bb14786944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_runs_created_by_user_id'), 'payroll_runs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_id'), 'payroll_runs', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_period_end'), 'payroll_runs', ['period_end'], unique=False)
    op.create_index(op.f('ix_payroll_runs_period_start'), 'payroll_runs', ['period_start'], unique=False)
    op.create_index(op.f('ix_payroll_runs_status'), 'payroll_runs', ['status'], unique=False)
    op.create_table('payroll_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('worker_profile_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('total_deduction_amount', sa.Integer(), nullable=False),
    sa.Column('net_amount', sa.Integer(), nullable=False),
    sa.Column('attendance_days', sa.Integer(), nullable=False),
    sa.Column('half_days', sa.Integer(), nullable=False),
    sa.Column('absent_days', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_profile_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'assignment_id', name='uq_payroll_item_run_assignment')
    )
    op.create_index(op.f('ix_payroll_items_assignment_id'), 'payroll_items', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_payroll_items_id'), 'payroll_items', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_items_payment_status'), 'payroll_items', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payroll_items_payroll_run_id'), 'payroll_items', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_items_worker_profile_id'), 'payroll_items', ['worker_profile_id'], unique=False)
    op.create_table('worker_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_item_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_item_id'], ['payroll_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_deductions_deduction_type'), 'worker_deductions', ['deduction_type'], unique=False)
    op.create_index(op.f('ix_worker_deductions_id'), 'worker_deductions', ['id'], unique=False)
    op.create_index(op.f('ix_worker_deductions_payroll_item_id'), 'worker_deductions', ['payroll_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_deductions_payroll_item_id'), table_name='worker_deductions')
    op.drop_index(op.f('ix_worker_deductions_id'), table_name='worker_deductions')
    op.drop_index(op.f('ix_worker_deductions_deduction_type'), table_name='worker_deductions')
    op.drop_table('worker_deductions')
    op.drop_index(op.f('ix_payroll_items_worker_profile_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_payroll_run_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_payment_status'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_assignment_id'), table_name='payroll_items')
    op.drop_table('payroll_items')
    op.drop_index(op.f('ix_payroll_runs_status'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_period_start'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_period_end'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_created_by_user_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    # ### end Alembic commands ###
